{"timestamp":"2025-07-14T08:10:04.625766","level":"info","event":"DAG bundles loaded: dags-folder","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-07-14T08:10:04.627072","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/activefence.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-07-14T08:10:21.316661","level":"info","event":"Anonymized telemetry enabled. See                     https://docs.trychroma.com/telemetry for more information.","logger":"chromadb.telemetry.product.posthog"}
{"timestamp":"2025-07-14T08:10:21.682932","level":"error","event":"Error processing Delta table: Operation not supported\n          \u001b[31m↳\u001b[0m the credential provider was not enabled\n           \u001b[31m↳\u001b[0m no providers in chain provided credentials\n","logger":"unusual_prefix_0aab8e1abe4a8f324d874f9a30de87ad63865522_activefence"}
{"timestamp":"2025-07-14T08:10:21.683196","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"AttributeError","exc_value":"'Client' object has no attribute 'persist'","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":867,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1159,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":397,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":216,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":239,"name":"execute_callable"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":81,"name":"run"},{"filename":"/opt/airflow/dags/activefence.py","lineno":319,"name":"embed_gold_data"}],"is_group":false,"exceptions":[]},{"exc_type":"OSError","exc_value":"Operation not supported\n          \u001b[31m↳\u001b[0m the credential provider was not enabled\n           \u001b[31m↳\u001b[0m no providers in chain provided credentials\n","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/opt/airflow/dags/activefence.py","lineno":269,"name":"embed_gold_data"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/deltalake/table.py","lineno":161,"name":"__init__"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-07-14T08:10:21.897975Z","level":"error","event":"[2025-07-14T08:10:21Z WARN  aws_config::imds::region] failed to load region from IMDS err=failed to load IMDS session token: dispatch failure: other: client error (Connect): tcp connect error: Connection refused (os error 111) (FailedToLoadToken(FailedToLoadToken { source: DispatchFailure(DispatchFailure { source: ConnectorError { kind: Other(None), source: hyper_util::client::legacy::Error(Connect, ConnectError(\"tcp connect error\", 169.254.169.254:80, Os { code: 111, kind: ConnectionRefused, message: \"Connection refused\" })), connection: Unknown } }) }))","chan":"stderr","logger":"task"}
{"timestamp":"2025-07-14T08:10:21.898478Z","level":"error","event":"[2025-07-14T08:10:21Z WARN  aws_config::imds::region] failed to load region from IMDS err=failed to load IMDS session token: dispatch failure: other: client error (Connect): tcp connect error: Connection refused (os error 111) (FailedToLoadToken(FailedToLoadToken { source: DispatchFailure(DispatchFailure { source: ConnectorError { kind: Other(None), source: hyper_util::client::legacy::Error(Connect, ConnectError(\"tcp connect error\", 169.254.169.254:80, Os { code: 111, kind: ConnectionRefused, message: \"Connection refused\" })), connection: Unknown } }) }))","chan":"stderr","logger":"task"}
{"timestamp":"2025-07-14T08:10:21.898984Z","level":"error","event":"[2025-07-14T08:10:21Z WARN  aws_config::imds::region] failed to load region from IMDS err=failed to load IMDS session token: dispatch failure: other: client error (Connect): tcp connect error: Connection refused (os error 111) (FailedToLoadToken(FailedToLoadToken { source: DispatchFailure(DispatchFailure { source: ConnectorError { kind: Other(None), source: hyper_util::client::legacy::Error(Connect, ConnectError(\"tcp connect error\", 169.254.169.254:80, Os { code: 111, kind: ConnectionRefused, message: \"Connection refused\" })), connection: Unknown } }) }))","chan":"stderr","logger":"task"}
{"timestamp":"2025-07-14T08:10:21.899444Z","level":"error","event":"[2025-07-14T08:10:21Z WARN  aws_config::imds::region] failed to load region from IMDS err=failed to load IMDS session token: dispatch failure: other: client error (Connect): tcp connect error: Connection refused (os error 111) (FailedToLoadToken(FailedToLoadToken { source: DispatchFailure(DispatchFailure { source: ConnectorError { kind: Other(None), source: hyper_util::client::legacy::Error(Connect, ConnectError(\"tcp connect error\", 169.254.169.254:80, Os { code: 111, kind: ConnectionRefused, message: \"Connection refused\" })), connection: Unknown } }) }))","chan":"stderr","logger":"task"}
{"timestamp":"2025-07-14T08:10:21.899805Z","level":"error","event":"[2025-07-14T08:10:21Z WARN  aws_config::imds::region] failed to load region from IMDS err=failed to load IMDS session token: dispatch failure: other: client error (Connect): tcp connect error: Connection refused (os error 111) (FailedToLoadToken(FailedToLoadToken { source: DispatchFailure(DispatchFailure { source: ConnectorError { kind: Other(None), source: hyper_util::client::legacy::Error(Connect, ConnectError(\"tcp connect error\", 169.254.169.254:80, Os { code: 111, kind: ConnectionRefused, message: \"Connection refused\" })), connection: Unknown } }) }))","chan":"stderr","logger":"task"}
{"timestamp":"2025-07-14T08:10:21.900233Z","level":"error","event":"[2025-07-14T08:10:21Z WARN  aws_config::imds::region] failed to load region from IMDS err=failed to load IMDS session token: dispatch failure: other: client error (Connect): tcp connect error: Connection refused (os error 111) (FailedToLoadToken(FailedToLoadToken { source: DispatchFailure(DispatchFailure { source: ConnectorError { kind: Other(None), source: hyper_util::client::legacy::Error(Connect, ConnectError(\"tcp connect error\", 169.254.169.254:80, Os { code: 111, kind: ConnectionRefused, message: \"Connection refused\" })), connection: Unknown } }) }))","chan":"stderr","logger":"task"}
