{"timestamp":"2025-07-13T14:13:33.007282","level":"info","event":"DAG bundles loaded: dags-folder","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-07-13T14:13:33.007922","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/activefence.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-07-13T14:13:36.690040","level":"info","event":"Columns :                       article_id  ...              load_timestamp\n0                   cql6vgwyv4xo  ...  2025-07-13T14:13:34.391988\n1                   cdxlqeyw95no  ...  2025-07-13T14:13:34.483214\n2                   cdxl0w1w394o  ...  2025-07-13T14:13:34.562522\n3                   c4g2ezl7xqyo  ...  2025-07-13T14:13:34.446230\n4  tech-now-chiles-lost-children  ...  2025-07-13T14:13:34.511569\n\n[5 rows x 5 columns]","logger":"unusual_prefix_0aab8e1abe4a8f324d874f9a30de87ad63865522_activefence"}
{"timestamp":"2025-07-13T14:13:36.730919Z","level":"error","event":"[2025-07-13T14:13:36Z WARN  aws_config::imds::region] failed to load region from IMDS err=failed to load IMDS session token: dispatch failure: other: client error (Connect): tcp connect error: Connection refused (os error 111) (FailedToLoadToken(FailedToLoadToken { source: DispatchFailure(DispatchFailure { source: ConnectorError { kind: Other(None), source: hyper_util::client::legacy::Error(Connect, ConnectError(\"tcp connect error\", 169.254.169.254:80, Os { code: 111, kind: ConnectionRefused, message: \"Connection refused\" })), connection: Unknown } }) }))","chan":"stderr","logger":"task"}
{"timestamp":"2025-07-13T14:13:36.735150Z","level":"error","event":"[2025-07-13T14:13:36Z WARN  aws_config::imds::region] failed to load region from IMDS err=failed to load IMDS session token: dispatch failure: other: client error (Connect): tcp connect error: Connection refused (os error 111) (FailedToLoadToken(FailedToLoadToken { source: DispatchFailure(DispatchFailure { source: ConnectorError { kind: Other(None), source: hyper_util::client::legacy::Error(Connect, ConnectError(\"tcp connect error\", 169.254.169.254:80, Os { code: 111, kind: ConnectionRefused, message: \"Connection refused\" })), connection: Unknown } }) }))","chan":"stderr","logger":"task"}
{"timestamp":"2025-07-13T14:13:36.738092Z","level":"error","event":"[2025-07-13T14:13:36Z WARN  aws_config::imds::region] failed to load region from IMDS err=failed to load IMDS session token: dispatch failure: other: client error (Connect): tcp connect error: Connection refused (os error 111) (FailedToLoadToken(FailedToLoadToken { source: DispatchFailure(DispatchFailure { source: ConnectorError { kind: Other(None), source: hyper_util::client::legacy::Error(Connect, ConnectError(\"tcp connect error\", 169.254.169.254:80, Os { code: 111, kind: ConnectionRefused, message: \"Connection refused\" })), connection: Unknown } }) }))","chan":"stderr","logger":"task"}
{"timestamp":"2025-07-13T14:13:36.748667Z","level":"error","event":"[2025-07-13T14:13:36Z WARN  aws_config::imds::region] failed to load region from IMDS err=failed to load IMDS session token: dispatch failure: other: client error (Connect): tcp connect error: Connection refused (os error 111) (FailedToLoadToken(FailedToLoadToken { source: DispatchFailure(DispatchFailure { source: ConnectorError { kind: Other(None), source: hyper_util::client::legacy::Error(Connect, ConnectError(\"tcp connect error\", 169.254.169.254:80, Os { code: 111, kind: ConnectionRefused, message: \"Connection refused\" })), connection: Unknown } }) }))","chan":"stderr","logger":"task"}
{"timestamp":"2025-07-13T14:13:36.751992Z","level":"error","event":"[2025-07-13T14:13:36Z WARN  aws_config::imds::region] failed to load region from IMDS err=failed to load IMDS session token: dispatch failure: other: client error (Connect): tcp connect error: Connection refused (os error 111) (FailedToLoadToken(FailedToLoadToken { source: DispatchFailure(DispatchFailure { source: ConnectorError { kind: Other(None), source: hyper_util::client::legacy::Error(Connect, ConnectError(\"tcp connect error\", 169.254.169.254:80, Os { code: 111, kind: ConnectionRefused, message: \"Connection refused\" })), connection: Unknown } }) }))","chan":"stderr","logger":"task"}
{"timestamp":"2025-07-13T14:13:36.754998Z","level":"error","event":"[2025-07-13T14:13:36Z WARN  aws_config::imds::region] failed to load region from IMDS err=failed to load IMDS session token: dispatch failure: other: client error (Connect): tcp connect error: Connection refused (os error 111) (FailedToLoadToken(FailedToLoadToken { source: DispatchFailure(DispatchFailure { source: ConnectorError { kind: Other(None), source: hyper_util::client::legacy::Error(Connect, ConnectError(\"tcp connect error\", 169.254.169.254:80, Os { code: 111, kind: ConnectionRefused, message: \"Connection refused\" })), connection: Unknown } }) }))","chan":"stderr","logger":"task"}
{"timestamp":"2025-07-13T14:13:36.758154","level":"error","event":"Bronze processing failed: Operation not supported\n          \u001b[31m↳\u001b[0m the credential provider was not enabled\n           \u001b[31m↳\u001b[0m no providers in chain provided credentials\n","logger":"unusual_prefix_0aab8e1abe4a8f324d874f9a30de87ad63865522_activefence"}
{"timestamp":"2025-07-13T14:13:36.758449","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"OSError","exc_value":"Operation not supported\n          \u001b[31m↳\u001b[0m the credential provider was not enabled\n           \u001b[31m↳\u001b[0m no providers in chain provided credentials\n","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":867,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1159,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":397,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":216,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":239,"name":"execute_callable"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":81,"name":"run"},{"filename":"/opt/airflow/dags/activefence.py","lineno":142,"name":"process_bronze"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/deltalake/writer/writer.py","lineno":106,"name":"write_deltalake"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/deltalake/writer/_utils.py","lineno":32,"name":"try_get_table_and_table_uri"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/deltalake/writer/_utils.py","lineno":47,"name":"try_get_deltatable"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/deltalake/table.py","lineno":161,"name":"__init__"}],"is_group":false,"exceptions":[]}]}
